language: r
warnings_are_errors: false
sudo: false
cache: packages

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'
