language: r
warnings_are_errors: true
sudo: false
cache: packages

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get update -qq
  - sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev -y

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && ./.push_gh_pages.sh
