language: r
warnings_are_errors: false
sudo: false
cache: packages

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'
